### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by diegobh** [RedEM-RP/redem_roleplay#1]
Thank you very much for this work, its really incredible ^^

But i got some errors that can't start the RP:
`[ERROR] ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (us(node:8088) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
ing password: YES)(node:8088) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

[ERROR] ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)`

I've set it up the right root and root pass.

server.cfg:
```
set es_enableCustomData 1
set mysql_connection_string "server=127.0.0.1;uid=root;password=myROOTPASS;database=redemrp"

#These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager-rdr3
ensure fivem
ensure hardcap
ensure rconlog
#ensure scoreboard
ensure IPL
ensure esplugin_mysql
ensure mysql-async
ensure redem
ensure redem_roleplay
ensure redem_identity
ensure redemrp_respawn
```

resources folder:

- [redemrp]
-- redem_roleplay
-- redemrp_identity
-- redemrp_respawn
- async
- esplugin_mysql
- mysql-async
- redem

I'm using MySQL v5.7.28
Tried connect on the same machine as mysql is running...

Any idea how fix it, please???

Thank you very much!!!

FOUND THE ERROR!
The mysqlserver was using port 3308 instead 3306. I just changed it back to port 3306 and it's all right!!! Ty!!!!

**Comment by kanersps** [comment]
An issue with your connection string as you noticed already

/close
