### ISSUE TITLE
New update broke respawn and character

### ISSUE THREAD

**Issue by diegobh** [RedEM-RP/redem_roleplay#11]
3 major bugs found:

1) Before characte creation screen i selected to spawn at Saint Denis. After selcted the spawn, the create character spawn screen shows up and i created my character.
After finished, i spawned at Vallentine. Not saint denis. 

2) Death is bugged now. I died, but the text saying i'm dead don't shows up, neighter the respawn time. I waited and didn't respawn. So i used the command /respawn.

3) Create character screen pops up again. [FIXED]
After /respawn command, the screen to create character shows up again. Went toi the console and saw the error:
[ERROR] [MySQL] [redemrp_skin] An error happens on MySQL for query "SELECT * FROM skins WHERE `identifier`='steam:XX0XXX101XXXXXX' AND `charid`=1;": ER_NO_SUCH_TABLE: Table 'redemrp.skins' doesn't exist
- You have to import again sql from redemrp_skin ^^

4) Character creation back button freezes the game/don't work and the Heads have diferent skin tones. The options to select skin tone and head types are on different screens. I suggest put one below the other, to allow us config our character easier. And the last one is hair. hair types are showing with different colors on the same option. Would be better one option to choose hair style and one to select the color of hair style. ;)

And one last suggestion (not a bug :D):
Create 2 tables: banks and banksAccounts. Banks to store the id of the banks e.x: ID (int, primary): 1 / Name(varchar): Strawberry's Bank / menuCoords(varchar): x, y, z to store the coords to appears the menu to players open bank. like: Press E to open your bank account / blipCoords(varchar): x,y,z (coords to shows up on map the blip of the Bank) :D
And banksAccounts table: id (int, primary) / idBank (int, id from banks table) / idCharacter (id from characters table, user's id) / money (float): money the player have stored on bank ^^
My idea is shows up to users: Press E to open bank account after player get on range of the coords of the bank (menuCoords) and i would like to make each bank individual. E.G. if he deposit on strawberry $100, he can pick it up on strawberry. If he deposits $10 at Saint Denis, he only can retrieve this $10 at saint denis. But he still have 100 on strawberry account and more 10 on saint denis.
And add one option on all mails (train stations) to the player can get their balance for all banks. Like as he had requested each bank your balance and received on mailbox ;) So he can see their balance with no problems :D
Press E to get your banks balance. And one nui just showing up:
Strawberry Bank: $100
Saint Dennis Bank: $10
...
Total from all Banks: $110

**Comment by amakuu** [comment]
Umm gold is smth different than bank.
We don't want to make RedM:RP same like FiveM. So We are trying something different!

**Comment by diegobh** [comment]
Nice!!! ;) 
I'm looking for. 
U're doing a wonderful job, thanks!!!!

**Comment by amakuu** [comment]
Can you update every Redem:RP resources and try again?
