### ISSUE TITLE
Attempt To Index A Nil Value (field '?')

### ISSUE THREAD

**Issue by brad-lesh** [RedEM-RP/redem_roleplay#14]
SCRIPT ERROR: @redem_roleplay/server/sv_db.lua:67: attempt to index a nil value (field '?')
> ref (@redem_roleplay/server/sv_db.lua:67)
>  (@mysql-async/mysql-async.js:14898)

Been getting this problem lately. Database is up to date and connections work good.

What could be the problem?

**Comment by amakuu** [comment]
Please follow the install guide.
/close
