### ISSUE TITLE
Map disable after death

### ISSUE THREAD

**Issue by PercyGaming** [RedEM-RP/redem_roleplay#16]
![image](https://user-images.githubusercontent.com/58794859/71781521-16c60280-2fd0-11ea-9909-ebd441e12cd6.png)
Is it normal not to have the map after you're dead?

edit : If I die by a horse I still have the map but if a pnc or player kills me I don't have it anymore!

**Comment by amakuu** [comment]
please update to the newest version and follow install instructions.
