### ISSUE TITLE
redemrp NPC

### ISSUE THREAD

**Issue by Matetv** [RedEM-RP/redem_roleplay#17]
Greetings ..
How can I spawn NPC?
According to sv_entities.lua this should work. But it just doesn't work!

**Comment by Matetv** [comment]
entity("npc", {x = -308.75, y = 791.09, z = 117.8}, "NPC-01", { hash = "A_C_Horse_Arabian_White" })

**Comment by amakuu** [comment]
the code should be placed in sv_entites.lua
