### ISSUE TITLE
[Request] List out available icons you can pass into 0x26E87218390E6729

### ISSUE THREAD

**Issue by Henry12116** [RedEM-RP/redem_roleplay#24]
Looking [here](https://github.com/RedEM-RP/redem_roleplay/blob/master/client/cl_notification.lua#L5-L28) we can see that `tick` is an example `icon` you can use for these notifications. I wanted to know if there is a list out there containing _all_ of the native icons we can use and if said list can be included in the `cl_notification.lua` documentation.

I would be happy to submit the PR myself I just don't have the list of icons 🙂

**Comment by amakuu** [comment]
I'll think about it
