### ISSUE TITLE
bug money and xp

### ISSUE THREAD

**Issue by always91** [RedEM-RP/redem_roleplay#26]
[https://cdn.discordapp.com/attachments/534848716629213184/767822030912618498/Cattura.PNG](url)

I have this problem when i sell i buy items with cents

**Comment by imthatguyhere** [comment]
#27 should resolve this if you want to try it.

**Comment by always91** [comment]
not fixed same problem xp

**Comment by imthatguyhere** [comment]
Fair point. I don't use XP, so it was never applied to it at all. What kind of rounding would make sense for XP? You have the code, you could try some out. It's super easy.

**Comment by always91** [comment]
and if we want to add 0.5 XP for a sales-work etc ...
