### ISSUE TITLE
Money hud isn't updating

### ISSUE THREAD

**Issue by diegobh** [RedEM-RP/redem_roleplay#3]
Good!

The money hud isn't updating. I added and removed some money. The database added or removed with success but the hud just don't update. 
I noticed that hud updates only i rejoin server or with a server restart...
Maybe im doing something wrong?

Thank you!!!!

**Comment by RedrumRP** [comment]
Event listeners aren't named correctly. Should be prefixed with redemrp: instead of redem:

**Comment by amakuu** [comment]
fixed.
/close
