### ISSUE TITLE
impossible to put admin on server

### ISSUE THREAD

**Issue by tonyonline6120** [RedEM-RP/redem_roleplay#55]
Hello, it is absolutely impossible for me to put myself as admin on the server, the permissions table remains empty and in characters no place is provided for the server to find my admin group, how should I go about it?
Sorry to open a post for this but your discord links no longer work

**Comment by MuriloBada** [comment]
Howdy!! You need to set yourself in the first time in the permissions table manually, so you can access the others commands that need permission. Just place your steam hex in there and hit /logout that should work.

Discord link: https://discord.gg/fhKk6eTEcn

**Comment by tonyonline6120** [comment]
it's ok thank you
